--liquibase formatted sql

--changeset gbabiuc:create-books-schema splitStatements:false
CREATE SCHEMA IF NOT EXISTS books;

--changeset gbabiuc:create-users-schema splitStatements:false
CREATE SCHEMA IF NOT EXISTS users;

--changeset gbabiuc:create-books-table splitStatements:false
CREATE TABLE IF NOT EXISTS books.books
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn             VARCHAR(20)  NOT NULL,
    title            VARCHAR(255) NOT NULL,
    year             BIGINT,
    copies_available BIGINT
);

--changeset gbabiuc:create-authors-table splitStatements:false
CREATE TABLE IF NOT EXISTS books.authors
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

--changeset gbabiuc:create-book_to_author-table splitStatements:false
CREATE TABLE IF NOT EXISTS books.book_to_author
(
    book_id   BIGINT NOT NULL REFERENCES books.books (id),
    author_id BIGINT NOT NULL REFERENCES books.authors (id)
);

--changeset gbabiuc:create-categories-table splitStatements:false
CREATE TABLE IF NOT EXISTS books.categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

--changeset gbabiuc:create-book_to_category-table splitStatements:false
CREATE TABLE IF NOT EXISTS books.book_to_category
(
    book_id     BIGINT NOT NULL REFERENCES books.books (id),
    category_id BIGINT NOT NULL REFERENCES books.categories (id)
);

--changeset gbabiuc:create-users-table splitStatements:false
CREATE TABLE IF NOT EXISTS users.users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idn        VARCHAR(12)  NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL
);

--changeset gbabiuc:create-contacts-table splitStatements:false
CREATE TABLE IF NOT EXISTS users.contacts
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type  VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL
);

--changeset gbabiuc:create-user_to_contact-table splitStatements:false
CREATE TABLE IF NOT EXISTS users.user_to_contact
(
    user_id    BIGINT NOT NULL REFERENCES users.users (id),
    contact_id BIGINT NOT NULL REFERENCES users.contacts (id)
);

--changeset gbabiuc:create-borrow_history-table splitStatements:false
CREATE TABLE IF NOT EXISTS books.borrow_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT REFERENCES users.users (id),
    book_id     BIGINT REFERENCES books.books (id),
    borrow_date DATE NOT NULL,
    return_date DATE
);

--changeset gbabiuc:add-deleted-table-to-books-table splitStatements:false
ALTER TABLE books.books
    ADD deleted BOOL DEFAULT FALSE NOT NULL;

--changeset gbabiuc:create-function-decrement_book_quantity splitStatements:false
CREATE OR REPLACE FUNCTION books.decrement_book_quantity()
    RETURNS TRIGGER AS
$$
BEGIN
    UPDATE books.books SET copies_available = copies_available - 1 WHERE id = NEW.book_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

--changeset gbabiuc:create-function-increment_book_quantity splitStatements:false
CREATE FUNCTION books.increment_book_quantity() RETURNS TRIGGER AS
$$
BEGIN
    UPDATE books.books SET copies_available = copies_available + 1 WHERE id = NEW.book_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

--changeset gbabiuc:create-trigger-decrement_book_quantity splitStatements:false
CREATE TRIGGER decrement_book_quantity
    AFTER INSERT
    ON books.borrow_history
    FOR EACH ROW
EXECUTE FUNCTION books.decrement_book_quantity();

--changeset gbabiuc:create-trigger-increment_book_quantity splitStatements:false
CREATE TRIGGER increment_book_quantity
    AFTER UPDATE
    ON books.borrow_history
    FOR EACH ROW
    WHEN (OLD.return_date IS NULL AND NEW.return_date IS NOT NULL)
EXECUTE FUNCTION books.increment_book_quantity();

--changeset gbabiuc:add-deleted-column-to-user-table splitStatements:false
ALTER TABLE users.users
    ADD deleted BOOL DEFAULT FALSE NOT NULL;