--liquibase formatted sql

--changeset gbabiuc:create-books-schema splitStatements:false
CREATE SCHEMA books;

--changeset gbabiuc:create-books-table splitStatements:false
CREATE TABLE books.books
(
    book_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn             VARCHAR(20)  NOT NULL,
    title            VARCHAR(255) NOT NULL,
    author           VARCHAR(255) NOT NULL,
    year             BIGINT,
    publisher        VARCHAR(255),
    genre            VARCHAR(255),
    copies_available BIGINT
);

--changeset gbabiuc:create-authors-table splitStatements:false
CREATE TABLE books.authors
(
    author_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_name VARCHAR(255) NOT NULL
);

--changeset gbabiuc:create-books_authors-table splitStatements:false
CREATE TABLE books.books_authors
(
    book_id   BIGINT,
    author_id BIGINT,
    FOREIGN KEY (book_id) REFERENCES books.books (book_id),
    FOREIGN KEY (author_id) REFERENCES books.authors (author_id)
);

--changeset gbabiuc:create-users-schema splitStatements:false
CREATE SCHEMA users;

--changeset gbabiuc:create-users-table splitStatements:false
CREATE TABLE users.users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255)        NOT NULL,
    last_name  VARCHAR(255)        NOT NULL,
    email      VARCHAR(255) UNIQUE NOT NULL,
    phone      VARCHAR(20),
    address    VARCHAR(255)
);

--changeset gbabiuc:create-borrow_history-table splitStatements:false
CREATE TABLE users.borrow_history
(
    borrow_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    book_id     BIGINT,
    borrow_date DATE NOT NULL,
    return_date DATE,
    FOREIGN KEY (user_id) REFERENCES users.users (user_id),
    FOREIGN KEY (book_id) REFERENCES books.books (book_id)
);
